### ISSUE TITLE
Suggestion: More steps in startup window

### ISSUE THREAD

**Issue by idbrii** [Jays2Kings/DS4Windows#1]
The startup window that tells you how to setup DS4Windows is great and makes it much easier to use.

I had two problems getting started (first time I connected a DS4 to my PC) that may be good additions to the window's text:
- The Bluetooth code is 0000
  - This is probably a common thing for all bluetooth devices, but I don't use many so I didn't know why it was failing to connect.
- You need to create a profile for DS4Windows to work.
  - It doesn't create a profile by default and it took me a bit before I realized that I needed to create one for anything to work (I thought it was just to customize my settings).

**Comment by Jays2Kings** [comment]
Good points, I'll be sure to add it in my next build.
