### ISSUE TITLE
"Start with Slide/Scroll off" does not work

### ISSUE THREAD

**Issue by Soul-Burn** [Jays2Kings/DS4Windows#11]
I have checked "Start with Slide/Scroll off" and verified it is set in the profile XML

```
<StartTouchpadOff>True</StartTouchpadOff>
```

However, the touch pad always starts on.
I have 3 profiles, each set like this. I disable the touchpad with PS+Touchpad hotkey and switch profile - the touchpad works again.

**Comment by Jays2Kings** [comment]
So it doesn't I'll look into why that is.
