### ISSUE TITLE
Crash when using R2 to run macro Alt-F4

### ISSUE THREAD

**Issue by Soul-Burn** [Jays2Kings/DS4Windows#13]
Set R2 to be a macro that clicks Alt-F4. Crashes application.

LMenu press
F4 press
F4 unpress
LMenu unpress

**Comment by Jays2Kings** [comment]
I've tried this macro out and had no problems, do other macros work for you? Does regular Keyboard mapping work for you?

**Comment by Soul-Burn** [comment]
Other macros seem to work.
There seems to be a case where the "press" is not recorded due to be being handled by another application leaving it with

LMenu press
F4 unpress
LMenu unpress

This seems to crash.

**Comment by Jays2Kings** [comment]
i'm not sure why the first f4 isn't recorded, but i found the error, and it will be fixed in the next update.
