### ISSUE TITLE
Solving exclusive mode woes

### ISSUE THREAD

**Issue by idbrii** [Jays2Kings/DS4Windows#14]
I boot my machine into Steam Big Picture and so when I connect my DS4, it always gives the "could not open exclusively" error. This often screws up other applications that want to use the useless DualShock controller instead of DS4Windows' Xinput controller.

I found a way to fix this: Disable "Wireless Controller".
- Open Device Manager
- In the Bluetooth section, there is a "Wireless Controller". Double click on it.
  - For me the Driver Version is 6.3.9600.17278
- Select the Driver tab
- Click Disable
- Reboot your computer

Now you never get errors about Exclusive Mode.

It looks like [you can disable devices programmatically](http://stackoverflow.com/questions/1438371/win32-api-function-to-programmatically-enable-disable-device). I'm not sure if there's a way to uniquely identify the DS4 and since it appears to be a generic driver, silently disabling it sounds like a bad idea, but might be a good option to add.

**Comment by idbrii** [comment]
FYI, I've noticed that this process causes this error in [Unity](http://unity3d.com/) in the Console log on startup:

```
<RI.Hid> Failed to create device file:
20 The process cannot access the file because it is being used by another process.
```

However, using gamepad 1 (wired Xbox360 controller) and 2 (DS4Windows) still works fine so I don't think it should have problems. I wasn't able to use these two controllers before (although that may be due to #15).

I've only just figured this out today. I can report back if I find problems with this setup.

**Comment by Jays2Kings** [comment]
Yeah I rather not do something like that because toggling with hardware sounds like an all around bad idea. I'll try testing that out later, but I'll try it out, and see how it works.

Also I've used unity too, it's nothing to worry about.

**Comment by ENunn** [comment]
I know this is over a year old, but this didn't do crap. Worked before though
