### ISSUE TITLE
Add support for the official Sony DUALSHOCK 4 USB Wireless Adapter

### ISSUE THREAD

**Issue by GuidoFida** [Jays2Kings/DS4Windows#154]
This is the adapter I'm talking about
https://www.playstation.com/en-us/explore/accessories/dualshock-4-usb-wireless-adaptor/

It's still for pre-order on most places but I was about to get one from gamestop
http://www.gamestop.com/accessories/dualshock-4-usb-wireless-adapter/134132

I was able to use x360ce with the adapter but I would prefer to use DS4Windows instead.

**Comment by ghost** [comment]
I second that.

I bought the Adapter but it doesn't show up in ds4windows.

Would be great to be able to use it.

**Comment by bryale12** [comment]
The USB Adapter fixed the headphone jack issue it would be great if they added support.

**Comment by Vanquo** [comment]
Someone named boganhobo on reddit made a fork that adds support for the adapter.
https://www.reddit.com/r/pcgaming/comments/5387gn/i_updated_ds4windows_with_compatibility_for_sonys/
https://github.com/boganhobo/DS4Windows

Another user on reddit SonicFreak94 made a fork merging boganhobo's tweak along with a few other fixes.
https://github.com/SonicFreak94/DS4Windows

**Comment by ghost** [comment]
Removed

**Comment by Jays2Kings** [comment]
I'm currently working in merging this fix as well as a few others, hopefully by the week's end I shall release an update.

**Comment by ghost** [comment]
@Jays2Kings 

AWESOME, thank you so much!

**Comment by Vanquo** [comment]
@J0JC 
Not sure what you we're looking at. Here's the recent commits that were from a few days ago.
https://github.com/boganhobo/DS4Windows/commit/051029095add79ac82b0d403c5d47dd4416212ad
https://github.com/SonicFreak94/DS4Windows/commit/d10ea2e54e13ee5c48414aba5ba22791329e8ba8

@Jays2Kings
That's fantastic news! Thanks for the update.

**Comment by ghost** [comment]
@Vanquo 

My bad.

**Comment by Jays2Kings** [comment]
As of version 1.4.5 support for the adapter has been added. I haven't been able to get an adapter yet to test, but seeing that this has been tested by others, this issue will be marked closed.

**Comment by styygeli** [comment]
I have the adapter and I installed DS4W last night.

Works just fine (after reboot) :)

Tested with Steam Big Screen and the Assassins Creed Unity
