### ISSUE TITLE
Uninstall Driver

### ISSUE THREAD

**Issue by augiem** [Jays2Kings/DS4Windows#16]
There isn't an uninstall driver button and I can't find any information about how to uninstall the DS4 driver.

**Comment by DerekTurtleRoe** [comment]
It depends on your operating system. but it should be in device manager on Windows 7 and above. Just uninstall it there.

**Comment by Jays2Kings** [comment]
An uninstall button will only show up if you have a virtual bus driver folder, which is added if you install the driver from DS4Windows itself. If you don't you can install it from device manager as vgturtle said, or you can download the driver's install/uninstall tool here: ds4windows.com/Files/Virtual Bus Driver.zip

**Comment by augiem** [comment]
Fixing the link so it's downloadble:
http://ds4windows.com/Files/Virtual%20Bus%20Driver.zip

**Comment by aksteele1** [comment]
I cant seem to get this program working, i think i  never told a place to go, and now it wont install and i am not sure how to make sure it is uninstalled...i can get the updater to work, but when i click the ds4w program it just sits and never opens... i just want to start over with this but am not sure how...i just need to get back to the original install process

**Comment by milkyjoe2** [comment]
how do i do it? i want to uninstall ds4windows (because of low sensitivity of R2 button), and i force installed the virtual bus driver thing, but i don't know what to look for in device manager? (windows 10)

**Comment by DerekTurtleRoe** [comment]
@milkyjoe2 It should be called Virtual Bus Driver, as far as I remember. Virtual something, at least. If you already removed the driver, it won't show up in the device manager, and all you have to do now is delete all the DS4Windows files from your hard drive.

**Comment by milkyjoe2** [comment]
even though i have installed a) ds4windows b) VBD (with force install) i can't find it in device manager... do you know which category it would be in and what to do if it's not there? @vgturtle127  something must be installed bc controller still works with ds4w in games

**Comment by DerekTurtleRoe** [comment]
@milkyjoe2 Not sure, on my system it was obvious which one it was. If it isn't there, then the driver might just be installed but not the software. The DS4 is still recognized by Windows, and some games natively support it without drivers. It can also be detected by Steam.

I don't know, though. You may want to take a look at all the installed drivers in device manager and see if you can find it there and uninstall it.
