### ISSUE TITLE
V2 controller not recognised

### ISSUE THREAD

**Issue by DVLP** [Jays2Kings/DS4Windows#183]
I'm successfully using DS4 controller with DS4Windows and it's awesome, so I bought another controller for split screen games. Unlike the first one the now controller is **V2**. It's connected to my system through bluetooth just like the first one but it's not being recognised by DS4Windows :/

**Comment by cassava** [comment]
Possibly duplicate of #177.

**Comment by TristanYoung** [comment]
Definitely a duplicate.  I'm testing an updated version of DS4Windows with the PID for the new controllers added.  So far, seems to be working.

**Comment by DVLP** [comment]
Yeah so I made a duplicate, close please
