### ISSUE TITLE
DS4Windows is killing Steam

### ISSUE THREAD

**Issue by chris94oha** [Jays2Kings/DS4Windows#195]
Hey ho,
I'm using a ds4 controller, which is connected via a USB cable to my PC. As soon as I connect my controller while steam is running, it just shuts down steam. If I have my controller connected before I start steam, steam just won't start at all. When I remove all DS4Windows drivers and files it works perfectly fine. I even reinstalled windows today and it still happens (fresh install with a fresh ISO on a fresh 3.0 stick). I tried USB 3.0 and USB 2.0 ports, same results on both.

I'm Running Windows 10 build 1607

If system specs would be helpful:
i5 6600k
gtx 1060
16gb ddr4
Asrock Fatal1ty K4
120GB SSD for windows (ds4windows)
1TB Drive for steam and other stuff.

**Comment by conc1erge** [comment]
have you tried opening DS4Windows first then steam?
