### ISSUE TITLE
Add the options to dim the Lightbar, test rumble motors individually and disable keyboard + mouse

### ISSUE THREAD

**Issue by luizberti** [Jays2Kings/DS4Windows#2]
In the original DS4Tool, we had the option to select the intensity of of the Lightbar's lamp. In this one, it's unchangeable, and seems to default to 100%. Two problems in that, controller battery will die faster, and that in a dark room, this feels like a light beam from the sun. It's surprisingly bright and causes reflections on the TV, not to mention it lights up the entire room.

Second feature request is a minor one, the ability to test rumble motors individually. That was something doable in XInputTest, but it doesn't work in Windows 8.1 it seems. Your tool however implemented most of it's functionality however, this is the only thing I missing.

The third one is probably the most technically difficult, but also one of the biggest features you could have. Some games don't disable mouse and keyboard controlling when a controller is active. That means that even the slightest motion from the mouse, say from a loud subwoofer, puts the game in KB+Mouse mode, and moves the view with the mouse. A Touchpad gesture that enables/disables the keyboard and mouse would be immensely helpful in these scenarios. Instead of crawling to the back of the desk and unplugging the peripherals, a quick flick through the Touchpad would temporarily disable them.

I'm not sure if the last one can even be accomplished, I am not a Windows programmer nor am I familiar with the .NET FW, but it would be an amazing feature to have. In any case your tool is insanely awesome and I would like to thank you for your efforts and hard work. Keep it up!

**Comment by Jays2Kings** [comment]
1) You can change the light bar intensity value by lowering all three lightbar sliders
2) I can add that
3) Yeah that's just not possible, plus I rather not go disabling other hardware.
