### ISSUE TITLE
Dualshock 4 will not work with DS4Windows or connect with my PS4.

### ISSUE THREAD

**Issue by BipolarRooster** [Jays2Kings/DS4Windows#207]
I had recently installed DS4Windows for my laptop, it worked great and I was pretty happy with it! Sadly after about 3 hours it stopped working. I then switched over to my PS4 and the controller doesn't want to connect with it anymore either, I tried resetting the controller, using bluetooth instead of USB for my PC. The Dualshock 4 controller didn't connect through any USB-cable with my PS4 and I can't seem to find anyone with the same issue as me, that managed to get the issue solved. Is there anything I might be forgetting or do I just have bad luck? Thanks for any help!

**Comment by Peekofwar** [comment]
Your DualShock®4 controller may be **damaged**.
