### ISSUE TITLE
Buttons lockup

### ISSUE THREAD

**Issue by rlex** [Jays2Kings/DS4Windows#22]
...maybe something with drivers. 
Sometimes, while playing with ds4windows, my controller (or, most likely, driver) lock ups pressing one button. This can only be solved by restarting ds4windows and/or scpserver.

I installed InputMapper and it does not have this issue, tested for like 2-3 hrs, while with ds4w it happens after 10-20 mins. I also noticed that file creation date of ScpServer.exe is newer in InputMapper. Maybe you just use outdated drivers?

Looking forward to see this fixed, i loved your app more than IM.

**Comment by rlex** [comment]
Forgot some details:
Win 8.1
Both bluetooth and wired

**Comment by rlex** [comment]
Some additional info: when this happens, LED switches to white and controller stops responding. Stop/Start in GUI helps with this.

**Comment by Jays2Kings** [comment]
Are you running ScpServer with DS4Windows? Because you don't need to run it (in fact DS4Windows doesn't even come with ScpServer, just the driver). I'm not sure what the results are when you run both at the same time.

**Comment by rlex** [comment]
i uninstalled original scpserver before installing ds4windows.

In fact, i hasn't experienced that issue for a very long time (like 2 weeks). Maybe that was something GTA-related but two batman games went absolutely smooth for me.

i'll just close it for now and re-open in case this will appear again.
