### ISSUE TITLE
WiFi Interference?

### ISSUE THREAD

**Issue by cll0ud** [Jays2Kings/DS4Windows#223]
Hi, I've been using DS4Windows for a couple days and I've been having a few issues with my internet. At first I thought it was just random but then I noticed that it would stop working everytime I pair my DS4 and start DS4Windows... WiFi seems connected but internet just stops working. I thought it was interference with my router (it's really cheapy, internet provider gave it for free) but I have 2 different WiFi connections in my house and it also happens with the other one (router is better but I can't say it's a good one).
Yesterday I got it working after unchecking "Hide DS4 Controller". It worked fine for hours but today when I starting using it again, internet just wouldn't work. I tried rechecking/unchecking that option again but no deal.
So summarizing: Internet works fine with controller paired but as soon as I start using DS4Windows internet goes down.
I'm using a Dell Inspiron 15r, original Bluetooth and WiFi driver.
Thank you for your time.

**Comment by ghost** [comment]
Just wondering, do you have the same problems when using a bluetooth speaker or other bluetooth device? Because if that's the case, there's nothing that can be fixed in software.

One thing you can try is using a 5GHz wifi connection (instead of the normal 2.4Ghz kind which bluetooth would interfere with), although this depends on the router, and might not be available with what you have.

**Comment by cll0ud** [comment]
Hi ajmck, thank you for your answer.
I use a few bluetooth devices, like my phone, one of those Microsoft one-sided headset and a headphone. Never had any issues.
I recently installed Steam's beta update - it comes with Dualshock 4 support so you can use it just like the Steam Controller - it works fine, I didn't have any problem with the WiFi while playing using it. But it doesn't have half the options DS4Windows have and it's still kinda buggy.
My router doesn't support 5GHz and at this moment I can't afford one so I won't be able to test this :(

**Comment by repoman728** [comment]
it is breaking my wifi !!!!
