### ISSUE TITLE
Could it add support for DS3 Controller？

### ISSUE THREAD

**Issue by realkkk** [Jays2Kings/DS4Windows#27]
Motioninjoy is the only one which support sixaxis for DS3, but it  is no longer updated and  not supported with win8.1
Wish DS4Windows could add support for DS3 Controller. 
Sorry for my poor English.

**Comment by Workings** [comment]
Use this instead:
http://forums.pcsx2.net/Thread-XInput-Wrapper-for-DS3-and-Play-com-USB-Dual-DS2-Controller

**Comment by realkkk** [comment]
Yeah! The SCP-DS is a wonderful xinput driver for DS3, But it couldn't use sixaxis motion with DS3  Controller. 
Well, Thansk for your help.

**Comment by Jays2Kings** [comment]
Sorry I don't plan to add support for the DS3, it's far too different from the DS4 and it's settings and it would just clutter everything up in the program
