### ISSUE TITLE
Unable to bind AppsKey

### ISSUE THREAD

**Issue by displayerror** [Jays2Kings/DS4Windows#3]
Hello,
Not sure if a bug or my system config, but I'm unable to bind AppsKey (via scan code or macro) to anything other than the PS/Guide button.

Using DS4W: 1.4.161 / Win7 x64 

Okay thanks!

**Comment by Jays2Kings** [comment]
I haven't gotten to test it yet sorry about that, I'll try to for the next update

**Comment by displayerror** [comment]
Hey, you got it working!
Thank you so much for fixing it :D
