### ISSUE TITLE
"Scroll" can be negative, but is parsed as unsigned (System.OverflowException)

### ISSUE THREAD

**Issue by michael-fadely** [Jays2Kings/DS4Windows#49]
In the profile editor, the `Scroll` numeric up/down (for mouse emulation) can be a negative number, but it's parsed as an unsigned integer which throws an exception on negative values. I came across this since I imagined setting a negative value would invert the scroll direction.

[Log here.](https://gist.github.com/7145024423635403135d)

**Comment by michael-fadely** [comment]
I've opened pull request #53 to fix this issue. Ping @Jays2Kings - acknowledgement at least would be nice.

**Comment by Jays2Kings** [comment]
My mistake about this, I saw this issue earlier, but i forgot about it by the time i updated it earlier, the newest version (1.4.31) fixes the issue.
