### ISSUE TITLE
PS4 won't recognize controller after using in PC

### ISSUE THREAD

**Issue by MithelCelestia** [Jays2Kings/DS4Windows#490]
At first I thought its just me not stopping the program before I close or unplug the controller but when i tried to use the controller on the ps4 after stopping the program in the pc, the ps4 still won't recognize the controller. I had to reconnect the controller to the ps4 with a usb cord in order for the console to recognize the controller again.

**Comment by GingerAdonis** [comment]
Just as a heads up: This fork/version of DS4Windows is outdated. An improved version is being actively maintained by Ryochan7.

> https://github.com/Ryochan7/DS4Windows/releases

**Comment by abnerfs** [comment]
That's normal the same happens when you use your DS4 with another PS4, you have to pair it again using the USB cable

**Comment by MithelCelestia** [comment]
I see. Thanks for clearing this up.
