### ISSUE TITLE
[Improvement suggestion] pair bluetooth using USB connection

### ISSUE THREAD

**Issue by scooterlord** [Jays2Kings/DS4Windows#525]
Hello @Jays2Kings and thanks for providing us with this piece of software. I would like to make a suggestion improvement, following the procedure used to pair the DS4 controller to the console.

Would it be easy for you to 'pair' the controller via bluetooth simply by plugging it in the USB port and hitting the PS button?

I think it would be great improvement UX wise and would help pair bluetooth with minimal effort.

**Comment by Limyx826** [comment]
Maybe you could try Ryochan7 fork version? Jay2Kings is kind of missing for some time.

**Comment by scooterlord** [comment]
Thanks, I will look into it
