### ISSUE TITLE
Failed to open x exclusively.

### ISSUE THREAD

**Issue by MastaNub** [Jays2Kings/DS4Windows#561]
https://prnt.sc/qsj7ma
I literally quit everything and it still doesn't want to launch in exclusive mode.

**Comment by Volkaru** [comment]
I noticed you closed this issue. Did you ever find a solution?

**Comment by MastaNub** [comment]
https://github.com/Jays2Kings/DS4Windows/issues/506#issuecomment-461490676 It worked once but now it isn't again. It's weird.
