### ISSUE TITLE
Editing Special Actions v1.4.52

### ISSUE THREAD

**Issue by MatharuG** [Jays2Kings/DS4Windows#579]
Hello!
I made a Special Action to check the DS4 Battery (Options + Share)
But when I have to edit it, I always get this error.
Then I have to Erase the Special Action, and create a new one everytime...

1. I can _Continue_ (doesn't close the app, and keeps everything working normally);;
2. I can _Close_ (Closes the App... duh)
3. And I can see the _Details_ (see below)
     System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em DS4Windows.SpecActions.LoadAction()
   em DS4Windows.SpecActions..ctor(Options opt, String edit, Int32 editindex)
   em DS4Windows.Options.btnEditAction_Click(Object sender, EventArgs e)
   em System.Windows.Forms.Control.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ButtonBase.WndProc(Message& m)
   em System.Windows.Forms.Button.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblies Carregados **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4150.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DS4Windows
    Versão do Assembly: 1.4.52.0
    Versão do Win32: 1.4.52
    Base de Código: file:///D:/DS4%20Windows/DS4Windows.exe
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4150.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4121.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Management
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Microsoft.CSharp
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Versão do Win32: 4.8.4150.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

![image](https://user-images.githubusercontent.com/26250877/76706501-ae2d8d00-66c6-11ea-834d-472efa3d57c9.png)

(Oh, and there's a typo on the Profile Editor:)
![image](https://user-images.githubusercontent.com/26250877/76706516-c7ced480-66c6-11ea-9b18-c9e1832708b1.png)

Anyway, thanks! Great program, and I hope we have more features in future versions!

**Comment by ayala-io** [comment]
You are posting in the old, no-longer-maintained DS4Windows repository (Jay2Kings).

Trying posting your issue here: https://github.com/Ryochan7/DS4Windows/issues

**Comment by MatharuG** [comment]
> 
> 
> You are posting in the old, no-longer-maintained DS4Windows repository (Jay2Kings).
> 
> Trying posting your issue here: https://github.com/Ryochan7/DS4Windows/issues

I didn't even knew there was a newer DS4 Windows...
In that case, I'm gonna try installing that one
Thanks!
