### ISSUE TITLE
Unable to use Exclusive Mode on Windows 10 Build 9879

### ISSUE THREAD

**Issue by slartibardfast** [Jays2Kings/DS4Windows#6]
It looks like Windows 10 9879 is locking the Wireless Controller preventing the use of Exclusive Mode / Hiding of the Wireless Controller.  

Sorry, I don't have Visual Studio setup yet to provide more information or debug this more properly. Though I'd report it anyway, Cheers!

**Comment by Jays2Kings** [comment]
There is nothing that can be done to fix this, like you said Windows 10 itself or the system takes the controller and pretty much any device. The only possible fix is for Microsoft to restore a service (specifically called Application Experience) which was removed from the newest build that stopped the system form taking the controller.

**Comment by slartibardfast** [comment]
thanks for the info!

**Comment by adamtmitchell** [comment]
It's not looking good for Windows 10 support then. Just installed the latest leaked build (10147) to see if there was any sign of a return for the Application Experience service and still nothing.

EDIT: Still no AE service in the latest public build (10158). I'm not sure it is coming back.

**Comment by BlueRaja** [comment]
I'm now seeing this issue under Windows 7 as well.
