### ISSUE TITLE
Exclusive mode not working?

### ISSUE THREAD

**Issue by Xev67** [Jays2Kings/DS4Windows#60]
I just updated to 1.4.4 and cannot play Fallout 4 with an inverted x-axis anymore. It seems to pick up the direct input now rather than the input from my profile where I swapped the left and right on the rightstick x-axis. DS4 says I'm in exclusive mode and Fallout 4 is not overriding the LED light colors, but it refuses to recognize any changes to joystick mappings made in my profile. Also had the y-axis inverted which is no longer working.

**Comment by Jays2Kings** [comment]
It's not a problem with exclusive mode, however i can fix this issue, please wait for the next version.

**Comment by Xev67** [comment]
I see. Exclusive mode was just a guess on my part.  I'm using the competition in the mean time,  but I want to say that I love your product and appreciate all your efforts!  Can't wait to switch back!

**Comment by Jays2Kings** [comment]
This issue is now fixed as of 1.4.401
