### ISSUE TITLE
Controller Gyro Vibration

### ISSUE THREAD

**Issue by worsiesousie** [Jays2Kings/DS4Windows#602]
Hi There

I have been using DS4 Windows for quite some time, and never had any issues until now.
Not sure what changed, as I didn't reinstall the software or anything, but for some reason, whenever I connect my PS4 controller now, whenever I tilt the controller in an upward direction, it starts to vibrate vigorously.

Not sure if this has something to do with the Gyro settings.
I have reinstalled the drivers and reinstalled DS4Windows as well, but it still happens.

Anyone know how to fix this, or had this issue before? It's quite annoying and I'm not sure how to fix it.

**Comment by elfumar** [comment]
> Hi There
> 
> I have been using DS4 Windows for quite some time, and never had any issues until now.
> Not sure what changed, as I didn't reinstall the software or anything, but for some reason, whenever I connect my PS4 controller now, whenever I tilt the controller in an upward direction, it starts to vibrate vigorously.
> 
> Not sure if this has something to do with the Gyro settings.
> I have reinstalled the drivers and reinstalled DS4Windows as well, but it still happens.
> 
> Anyone know how to fix this, or had this issue before? It's quite annoying and I'm not sure how to fix it.

S

**Comment by worsiesousie** [comment]
Update - I created a new profile and it is working now. Seems like only the Default Profile is making the controller vibrate when tilted.
