### ISSUE TITLE
Controller randomly goes off during game

### ISSUE THREAD

**Issue by itjeph** [Jays2Kings/DS4Windows#606]
I've been having this issue since I started using ds4windows 2 years ago and I've decided to finally speak up. I play a lot of online FIFA and 3 out 10 times my controller just randomly goes off or stops working in game. And if I alt + tab I lose the game. With the newest updates I can now see the log of what happened and it always says this 

`Gamepad data write connection is lost. Disconnecting the gamepad. LastErrorCode = 1167`

I get this so many times it's unbelievable. Any help on how to never see this again?

**Comment by mika-n** [comment]
You are posting in wrong web site. Based on the error message you are using Ryochan7/DS4Windows version and not this Jay2Kings version on this website (this Jay2kings version haven't been updated for years)
#587
