### ISSUE TITLE
Can't use until reboot as Dualshock

### ISSUE THREAD

**Issue by MrIronstone** [Jays2Kings/DS4Windows#651]
When my dualshock's battery dries, I plug it to my computer to charge it up, I can use it on charge while dualshock emulated profile is on but when I unplug my dualshock, I cannot use dualshock emulated profile again until reboot

**Comment by GingerAdonis** [comment]
Please note that this version of DS4Windows is dead. You can get up-to-date builds from here: https://github.com/Ryochan7/DS4Windows/releases

**Comment by MrIronstone** [comment]
Sorry, I was already using the latest version, I did not realize that I was on the wrong section. Thank you for the link.
