### ISSUE TITLE
Experience

### ISSUE THREAD

**Issue by Blu3Dev21x** [Jays2Kings/DS4Windows#679]
I used this for two weeks then someone logged into my account and changed my guns around and it kept kicking me out. Why would you guys build something with a trojan in it? Update: ended up being ps4 account logged in while I was using pc.

**Comment by mika-n** [comment]
?

who knows what you have installed and from where you downloaded it.

**Comment by Blu3Dev21x** [comment]
Updated

**Comment by alpharou** [comment]
Close the issue please, you are clogging up development
