### ISSUE TITLE
Warzone not detecting controller sometimes

### ISSUE THREAD

**Issue by Blu3Dev21x** [Jays2Kings/DS4Windows#697]
I will at times disconnect the controller to untangle the type c usb cable, and when i reconnect it the pc detects the controller, the ds4 does also but in game only the touch pad on the ps5 works not any of the buttons. I go through a process of restarting the game and pc over and over until it does. someone pease fix this.

**Comment by ghost** [comment]
Sadly this can't be fixed as for now since Jays2Kings is probably not taking care of this project anymore, he is still active on GitHub itself, but no any signs of activity on DS4Windows

**Comment by ghost** [comment]
Here is a fork that is being updated actively and your issue might be fixed: https://github.com/Ryochan7/DS4Windows, if not, open a issue there.

**Comment by Blu3Dev21x** [comment]
> I will at times disconnect the controller to untangle the type c usb cable, and when i reconnect it the pc detects the controller, the ds4 does also but in game only the touch pad on the ps5 works not any of the buttons. I go through a process of restarting the game and pc over and over until it does. someone pease fix this.

P

**Comment by Blu3Dev21x** [comment]
Moved to Ryochan development. That's the one I downloaded.
