### ISSUE TITLE
Try DS4Windows on Steam Big Picture; it works GREAT!!!!!

### ISSUE THREAD

**Issue by tetrisxz** [Jays2Kings/DS4Windows#82]

**Comment by DerekTurtleRoe** [comment]
@Jays2Kings I think this can be closed since this isn't really a forum or anything.

@tetrisxz Thanks for the feedback, but maybe use a forum or Reddit or something instead of a GitHub issue. :wink:

**Comment by tetrisxz** [comment]
no problem

**Comment by DerekTurtleRoe** [comment]
@tetrisxz We're glad you're excited about DS4Windows, though. I am pretty excited as well. :smile:
