### ISSUE TITLE
Feature Request: Microphone input socket

### ISSUE THREAD

**Issue by mjs1994** [Jays2Kings/DS4Windows#88]
Hey Jays2Kings,

I've been using DS4Windows for a while now and it seems to work perfectly every time, never really have any issues with it other than the odd latency drop when the controller is quite far away from the bluetooth reciever.

So, onto my feature request, is there anyway you can get the microphone input socket on the DS4 controller to pick up as a headset inside of Windows? 

Thanks!

**Comment by ajostergaard** [comment]
From the FAQ:

Is bluetooth audio support coming?

So long as I work by myself, never. I don't have the know-how to understand reverse engineering the DualShock 4 to enable its audio jack.

**Comment by mjs1994** [comment]
Sorry! Didn't see this on the FAQs, thanks for the response anyhow.

**Comment by ajostergaard** [comment]
On the other hand some people have been working on it recently... :) Checkout issue #17.
